name: Update Kubernetes infrastructure

on:
  pull_request:
    branches: [main]
    paths:
      - 'tf/**/*' # All terraform files
      - '.github/workflows/infrastructure.yaml' # This manifest
  push:
    branches: [main]
    paths:
      - 'tf/**/*' # All terraform files
      - '.github/workflows/infrastructure.yaml' # This manifest

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      working-directory: .github/workflows
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup yc cli
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name: Setup Terrafrom and Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.36.6
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Import Yandex key
        run: echo `echo QWxhZGRpbjpvcGVuIHNlc2FtZQ== | base64 --decode` > yandex-key.json
        working-directory: ${{ env.working-directory }}
      - name: bla
        run: echo ${{ env.working-directory }}/yandex-key.json
      - name: Create temporary IAM token
        run: export TF_VAR_k8s_token=$(yc iam create-token)
        
