name: Update Kubernetes infrastructure

on:
  pull_request:
    branches: [main]
    paths:
      - 'tf/**/*' # All terraform files
      - '.github/workflows/infrastructure.yaml' # This manifest
  push:
    branches: [main]
    paths:
      - 'tf/**/*' # All terraform files
      - '.github/workflows/infrastructure.yaml' # This manifest

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      BASE64: QWxhZGRpbjpvcGVuIHNlc2FtZQ==
      working-directory: .github/workflows
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import Yandex key
        uses: timheuer/base64-to-file@v1.1
        with:
          encodedString: ${{ env.BASE64 }}
          fileName: 'secret.json'
          fileDir: '/home/runner/yandex-cloud'

      - name: Setup Terrafrom and Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.36.6
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

        
